const actions = {
    GET_DATA_CURRENCY: "GET_DATA_CURRENCY",
    GET_DATA_CURRENCY_SUCCESS: "GET_DATA_CURRENCY_SUCCESS",
    GET_VAL_CURRENCY: "GET_VAL_CURRENCY",
    GET_VAL_CURRENCY_SUCCESS: "GET_VAL_CURRENCY_SUCCESS",
    GET_DATA: "GET_DATA",
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_DATA_WOMAN: "GET_DATA_WOMAN",
    GET_DATA_WOMAN_SUCCESS: "GET_DATA_WOMAN_SUCCESS",
    GET_DATA_MAN: "GET_DATA_MAN",
    GET_DATA_MAN_SUCCESS: "GET_DATA_MAN_SUCCESS",
    GET_DELTAI: "GET_DELTAI",
    GET_DELTAI_SUCCESS: "GET_DELTAI_SUCCESS"
  };
  export default actions;
  